version: 2.1

orbs:
  codacy: codacy/base@2.3.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          persist_to_workspace: true
          cmd: sbt "set scalafmtUseIvy in ThisBuild := false;update"
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt "scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          persist_to_workspace: true
          cmd: sbt compile
          requires:
            - populate_cache
      - codacy/sbt:
          name: test_and_coverage
          cmd: |
            sbt ";coverage;test;coverageReport;coverageAggregate"
            if [ -z ${CODACY_PROJECT_TOKEN+x} ]; then
              echo "CODACY_PROJECT_TOKEN not found. Skipping send coverage to Codacy."
            else
              bash <(curl -Ls https://coverage.codacy.com/get.sh)
            fi
          requires:
            - compile
      - codacy/sbt:
          name: package_artifacts
          persist_to_workspace: true
          cmd: |
            sbt "graalvm-native-image:packageBin"
            sbt "assembly"

            mkdir -p ~/workdir/artifacts/
            mv target/scala-2.13/codacy-gosec-assembly-$(cat .version).jar ~/workdir/artifacts/codacy-gosec-$(cat .version).jar
            mv target/graalvm-native-image/codacy-gosec ~/workdir/artifacts/codacy-gosec-$(cat .version)
          requires:
            - check_fmt
            - test_and_coverage
      - codacy/publish_ghr:
          name: publish_ghr
          path: ~/workdir/artifacts/
          filters:
            branches:
              only:
                - master
          context: CodacyGitHub
          requires:
            - package_artifacts
